Fix monitored element name in ttc validation
farao-community/gridcapa-cse-valid pull request #77
Opened 2023-01-16 10:30 UTC by vbochetRTE

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-17 12:24 UTC, oualid-aloui-rte commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/exception/LimitingElementBuildException.java
> + * Copyright (c) 2022, RTE (http://www.rte-france.com)
2023

2023-01-17 12:30 UTC, oualid-aloui-rte commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java
> +                    runDichotomyForExportCorner(timestampWrapper, cseValidRequest, tcDocumentTypeWriter, jsonCracUrl, raoParametersURL, network, cracCreationContext);
So you pass the shifted network to the dichotomy, while we are still waiting for an answer on this subject

2023-01-17 13:53 UTC, oualid-aloui-rte commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/LimitingElementHelper.java
> +    public static <T> Collector<T, ?, T> toOne() {
private

2023-01-17 15:10 UTC, oualid-aloui-rte approved these changes

2023-01-17 15:17 UTC, TheMaskedTurtle requested changes

2023-01-17 15:17 UTC, TheMaskedTurtle commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/CseValidHandler.java
> +            TLimitingElement tLimitingElement = LimitingElementHelper.getLimitingElement(dichotomyResult.getHighestValidStep(), cracCreationContext, network, fileImporter);
Why not importing RaoResult directly here instead of passing fileImporter ?

2023-01-17 15:17 UTC, TheMaskedTurtle commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/LimitingElementHelper.java
> +        for (FlowCnec flowCnec : crac.getFlowCnecs()) {
You forgot the filter on isOptimized property for the CNECs

2023-01-17 15:39 UTC, TheMaskedTurtle requested changes

2023-01-17 15:39 UTC, TheMaskedTurtle commented on gridcapa-cse-valid-app/src/main/java/com/farao_community/farao/cse_valid/app/dichotomy/LimitingElementHelper.java
> +    private static TCriticalBranch getCriticalBranch(FlowCnec worstCnec, CseCracCreationContext context, Network network) {
Name it cnec to remain generic

2023-01-18 09:01 UTC, TheMaskedTurtle approved these changes

2023-01-18 09:02 UTC, merged